draft version working from db module mvn test task
devonfw-forge/mrchecker-source pull request #21
Opened 2019-07-24 10:13 UTC by mpajonk

works from mvn DB module with test task, is it ok?

2019-07-24 10:15 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/devonfw-forge/mrchecker-source?pullRequest=21) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/devonfw-forge/mrchecker-source?pullRequest=21) before we can accept your contribution.<br/><hr/>**MPAJAK** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/devonfw-forge/mrchecker-source?pullRequest=21) it.</sub>

2019-08-12 18:49 UTC, tompalka requested changes

2019-08-12 18:49 UTC, tompalka commented on mrchecker-framework-modules/mrchecker-database-module/pom.xml
> +                        <db.password>1234</db.password>
Connection credentials (especially used only for testing purposes) shouldn't be present in pom.xml file

2020-09-15 06:52 UTC, closed without merging

2020-09-15 06:53 UTC, Pyskaczu commented
PR is broken. I'm going to reopen.