Other structure for Data Encryption Service
devonfw-forge/mrchecker-source pull request #52
Opened 2021-06-01 14:08 UTC by andrzejsamson

Changed the structure of Data Encryption Service. Removed redundant Model class and separated GUI from logic.

2021-06-01 14:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/devonfw-forge/mrchecker-source?pullRequest=52) <br/>All committers have signed the CLA.

2021-06-01 15:17 UTC, Pyskaczu requested changes

2021-06-01 15:17 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/main/java/com/capgemini/mrchecker/test/core/utils/encryption/controller/DataEncryptionController.java
> +	void onKey(JTextField keyTextField);
This should not be a part of DataEncryptionController

2021-06-01 15:17 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/main/java/com/capgemini/mrchecker/test/core/utils/encryption/controller/DataEncryptionControllerImp.java
> +	private final IView view;
Change IView to DataEncryptionView

2021-06-01 15:17 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/main/java/com/capgemini/mrchecker/test/core/utils/encryption/controller/DataEncryptionControllerImp.java
> +			showMessageDialog(null, "Could not encrypt because:\n" + e.getMessage());
Do not show dialog here. Throw unchecked exception and handle it in the view.

2021-06-01 15:17 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/main/java/com/capgemini/mrchecker/test/core/utils/encryption/controller/DataEncryptionControllerImp.java
> +	public void onDecrypt(CryptParams cryptParams) {
onEncrypt and onDecrypt have duplicates. Please refactor. You can use functional interface to implement that.

2021-06-01 15:17 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/main/java/com/capgemini/mrchecker/test/core/utils/encryption/controller/DataEncryptionControllerImp.java
> +	public void onKey(JTextField keyTextField) {
Let the view control opening files.

2021-06-01 15:17 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/main/java/com/capgemini/mrchecker/test/core/utils/encryption/view/DataEncryptionGUI.java
> +		dataEncryptionController = new DataEncryptionControllerImp(this);
This cannot be implemented like that. We need another way to instantiate and pass DataEncryptionController implementation.

2021-06-01 15:17 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/main/java/com/capgemini/mrchecker/test/core/utils/encryption/view/IView.java
> +	void setKeyFieldValue(String text, JTextField keyTextField);
Let's talk about that

2021-06-08 08:43 UTC, andrzejsamson commented
TODO: tests for business logic from app

2021-06-22 13:24 UTC, Pyskaczu requested changes

2021-06-22 13:24 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/test/java/com/capgemini/mrchecker/test/core/utils/encryption/DataEncryptionGUITest.java
> +	private static final IDataEncryptionController dataEncryptionController = new DataEncryptionController();
Using a concrete class. A mock should be used.

2021-06-22 13:24 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/test/java/com/capgemini/mrchecker/test/core/utils/encryption/DataEncryptionGUITest.java
> +		assertThat(result, startsWith("ENC("));
"ENC(" is coupled with DataEncrytpionController. Use mock instead and define return value.

2021-06-22 13:24 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/test/java/com/capgemini/mrchecker/test/core/utils/encryption/DataEncryptionGUITest.java
> +		dataEncryptionGUIFixture.fileChooser()
Do not use file. Give some explicit value.

2021-06-22 13:24 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/test/java/com/capgemini/mrchecker/test/core/utils/encryption/DataEncryptionGUITest.java
> +		assertThat(result, is(equalTo("")));
Code duplication?

2021-06-22 13:24 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/test/java/com/capgemini/mrchecker/test/core/utils/encryption/DataEncryptionGUITest.java
> +		dataEncryptionGUIFixture.button("decryptButton")
Do not use a file.

2021-06-22 13:24 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/test/java/com/capgemini/mrchecker/test/core/utils/encryption/DataEncryptionGUITest.java
> +		assertThat(result, is(equalTo("")));
Code duplication?

2021-06-22 13:25 UTC, Pyskaczu requested changes

2021-06-22 13:25 UTC, Pyskaczu commented on mrchecker-framework-modules/mrchecker-core-module/src/test/java/com/capgemini/mrchecker/test/core/utils/encryption/DataEncryptionGUITest.java
> +@IntegrationTest
Can be a UnitTest

2021-10-05 13:48 UTC, merged